package dej4501.model;
// Generated 07-11-2017 14:07:20 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto  implements java.io.Serializable {


     private Integer id;
     private String nombreProyecto;
     private String descripcion;
     private Date fechaIncio;
     private String estado;
     private long presupuestoInicial;
     private long presupuestoGastado;
     private int comunaId;

    public Proyecto() {
    }

    public Proyecto(String nombreProyecto, String descripcion, Date fechaIncio, String estado, long presupuestoInicial, long presupuestoGastado, int comunaId) {
       this.nombreProyecto = nombreProyecto;
       this.descripcion = descripcion;
       this.fechaIncio = fechaIncio;
       this.estado = estado;
       this.presupuestoInicial = presupuestoInicial;
       this.presupuestoGastado = presupuestoGastado;
       this.comunaId = comunaId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombreProyecto() {
        return this.nombreProyecto;
    }
    
    public void setNombreProyecto(String nombreProyecto) {
        this.nombreProyecto = nombreProyecto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaIncio() {
        return this.fechaIncio;
    }
    
    public void setFechaIncio(Date fechaIncio) {
        this.fechaIncio = fechaIncio;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public long getPresupuestoInicial() {
        return this.presupuestoInicial;
    }
    
    public void setPresupuestoInicial(long presupuestoInicial) {
        this.presupuestoInicial = presupuestoInicial;
    }
    public long getPresupuestoGastado() {
        return this.presupuestoGastado;
    }
    
    public void setPresupuestoGastado(long presupuestoGastado) {
        this.presupuestoGastado = presupuestoGastado;
    }
    public int getComunaId() {
        return this.comunaId;
    }
    
    public void setComunaId(int comunaId) {
        this.comunaId = comunaId;
    }




}


